'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,Mic,Pause,Play,RotateCcw} from 'lucide-react';
const ids=[44557,40741,1594,49878,40656,44559],names=['序章','采购物资','暴雪预警','庇护所','神秘来客','分支 A'];
const seconds=5, width=82,total=30;
export default function MovieEditor({back,notify}:{back:()=>void,notify:(s:string)=>void}){
const [index,setIndex]=useState(0),[playing,setPlaying]=useState(true),[holding,setHolding]=useState(false);const videos=useRef<(HTMLVideoElement|null)[]>([]),track=useRef<HTMLDivElement>(null),position=useRef(0),active=useRef(0),running=useRef(true),scrubUntil=useRef(0),programScroll=useRef(-1),hold=useRef<ReturnType<typeof setTimeout>|null>(null),recording=useRef(false);
function seek(t:number){t=Math.max(0,Math.min(total-.01,t));position.current=t;const i=Math.min(5,Math.floor(t/seconds));active.current=i;setIndex(i);videos.current.forEach((v,j)=>{if(!v)return;if(j===i){v.currentTime=Math.min(t-i*seconds,v.duration||seconds);if(running.current)v.play().catch(()=>{})}else v.pause()});}
function toggle(){running.current=!running.current;setPlaying(running.current);const v=videos.current[active.current];if(v){if(running.current)v.play().catch(()=>{});else v.pause()}}
useEffect(()=>{let frame=0;function tick(){const v=videos.current[active.current];if(v&&running.current&&performance.now()>scrubUntil.current){if(v.currentTime>=seconds-.025||v.ended){seek((active.current+1)*seconds>=total?0:(active.current+1)*seconds)}else position.current=active.current*seconds+v.currentTime;const el=track.current;if(el){const x=position.current/seconds*width;programScroll.current=x;el.scrollLeft=x}}frame=requestAnimationFrame(tick)}frame=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(frame);if(hold.current)clearTimeout(hold.current)}},[]);
function scroll(){const el=track.current;if(!el)return;if(Math.abs(el.scrollLeft-programScroll.current)<1.5)return;scrubUntil.current=performance.now()+180;running.current=true;setPlaying(true);seek(el.scrollLeft/width*seconds);}
function release(){if(hold.current)clearTimeout(hold.current);if(recording.current){recording.current=false;setHolding(false);notify('语音修改已记录')}}
return <section className="editor-page movie-editor"><div className="native-video" onClick={toggle}>{ids.map((id,i)=><video key={id} ref={v=>{videos.current[i]=v}} src={`media/${id}.mp4`} preload="auto" muted playsInline style={{opacity:index===i?1:0}} onLoadedData={()=>{if(i===active.current){const v=videos.current[i];if(v){v.currentTime=position.current-i*seconds;if(running.current)v.play().catch(()=>{})}}}}/>)}</div><header><button aria-label="返回故事与角色" onClick={back}><ArrowLeft/></button><span>冰封之前<small>自动保存</small></span><button onClick={()=>notify('正在导出影片')}>导出</button></header><div className="editor-control"><div className="playhead"><i/></div><div ref={track} className="clip-track movie-track" aria-label="影片时间线" tabIndex={0} onScroll={scroll} onPointerDown={()=>{scrubUntil.current=performance.now()+1000}}>{names.map((name,i)=><button key={name} className={index===i?'selected':''} onClick={()=>{running.current=true;setPlaying(true);seek(i*seconds);if(track.current){programScroll.current=i*width;track.current.scrollLeft=i*width}}}><img src={`media/${ids[i]}.jpg`} alt=""/><span>{name}</span><small>00:05</small></button>)}</div><button className="editor-play" aria-label={playing?'暂停':'播放'} onClick={toggle}>{playing?<Pause/>:<Play/>}</button></div><div className="editor-bottom"><div className="suggestions">{['重新生成','更紧张','增加特写','冰雪更大','换成夜景','加强对白'].map((s,i)=><button key={s} onClick={()=>notify(`已提交：${s}`)}>{i===0&&<RotateCcw/>}{s}</button>)}</div><button aria-label="长按录音" className={`voice-button ${holding?'holding':''}`} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);hold.current=setTimeout(()=>{recording.current=true;setHolding(true)},280)}} onPointerUp={release} onPointerCancel={release}><Mic/>{holding&&<span>松开发送</span>}</button></div></section>}
